### PR TITLE
Fixed url of Ronaldo repository.

### PR DESCRIPTION
**Pull request by cantoniazzi**

### CODE REVIEW

**Comment by cantoniazzi** [comment]
I was browsing through repositories and found that the URL was wrong.
I made the fork and ate it directly in the master (as it was just read.me and did not think it necessary to create a branch. I apologize if I missed the process).

**Comment by lferreira** [comment]
There is no problem don't create a branch @cantoniazzi. You have PR fot that is enough, thank you to contribute <3

**Comment by cantoniazzi** [comment]
Oh, that`s ok so. Thanks, guys!

**Comment by cantoniazzi** [comment]
Oh, that`s ok so. Thanks, guys! @lferreira

**Pull request merged**
